project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Shanaya Vanhooren"
  favicon: ""
  navbar:
    background: "#f1ebe0"
    foreground: "#22201c"
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: education.qmd
        text: Education
      - href: media.qmd
        text: Media
  page-footer:
    center: "© 2026 Shanaya Vanhooren"
    background: "#f1ebe0"

format:
  html:
    theme: [cosmo, theme.scss]
    toc: false
    link-external-newwindow: true
